"""Executive report renderer — C-level summary for non-technical stakeholders.

Generates a concise, PDF-ready Markdown executive summary with:
- Key metrics dashboard
- Top 3 risks
- Improvement impact estimates
- Overall health assessment
"""

from __future__ import annotations

from atlas_report.report_data import ReportData


def render_executive(data: ReportData) -> str:
    """Render a concise executive summary in Markdown.

    Args:
        data: ReportData with graph, findings, and scores.

    Returns:
        Markdown string suitable for executive presentation.
    """
    scores = data.scores
    findings = data.findings
    graph = data.graph

    # Health label
    if scores.complexity_score <= 40 and scores.fragility_score <= 30:
        health = "🟢 Excellent"
    elif scores.complexity_score <= 70 and scores.fragility_score <= 60:
        health = "🟡 Moderate"
    else:
        health = "🔴 At Risk"

    # Maturity label
    if scores.maturity_score >= 80:
        maturity = "Advanced"
    elif scores.maturity_score >= 50:
        maturity = "Developing"
    else:
        maturity = "Basic"

    lines = [
        f"# Executive Summary — {graph.name}",
        "",
        f"> **Overall Health: {health}** | CI Maturity: {maturity}",
        "",
        "## Key Metrics",
        "",
        "| Metric | Score | Status |",
        "|--------|-------|--------|",
        f"| Complexity | {scores.complexity_score:.0f}/100 | {'Low' if scores.complexity_score <= 40 else 'Medium' if scores.complexity_score <= 70 else 'High'} |",
        f"| Fragility | {scores.fragility_score:.0f}/100 | {'Low' if scores.fragility_score <= 40 else 'Medium' if scores.fragility_score <= 70 else 'High'} |",
        f"| CI Maturity | {scores.maturity_score:.0f}/100 | {maturity} |",
        f"| Pipeline Nodes | {scores.node_count} | — |",
        f"| Active Findings | {len(findings)} | — |",
        "",
    ]

    # Top risks
    critical_findings = [f for f in findings if f.severity.value in ("critical", "high")]
    if critical_findings:
        lines.append("## Top Risks")
        lines.append("")
        for i, f in enumerate(critical_findings[:3], 1):
            lines.append(f"{i}. **[{f.severity.value.upper()}]** {f.message}")
        lines.append("")
    else:
        lines.append("## Risks")
        lines.append("")
        lines.append("No critical or high-severity findings detected.")
        lines.append("")

    # Recommendations
    lines.append("## Recommended Actions")
    lines.append("")

    recommendations = []
    if scores.fragility_score > 50:
        recommendations.append("- **Reduce fragility** by pinning container images and reducing shared secrets")
    if scores.complexity_score > 60:
        recommendations.append("- **Simplify pipeline** by consolidating redundant steps and reducing fan-out")
    if scores.maturity_score < 50:
        recommendations.append("- **Improve maturity** by adding caching, retry policies, and environment isolation")
    if scores.missing_doc_types > 2:
        recommendations.append("- **Improve documentation** by adding missing RUNBOOK.md and CODEOWNERS files")
    if not recommendations:
        recommendations.append("- Pipeline is in good health. Continue monitoring for regressions.")

    lines.extend(recommendations)
    lines.append("")

    # Modernization notes
    if data.modernization_notes:
        lines.append("## AI Modernization Insights")
        lines.append("")
        lines.append(data.modernization_notes)
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by PipelineAtlas | Platform: {graph.platform or 'multi'}*")

    return "\n".join(lines)
