"""Markdown renderer — produces a full Markdown report with 8 sections."""

from __future__ import annotations

from atlas_sdk.enums import NodeType
from atlas_report.report_data import ReportData


def render_markdown(data: ReportData) -> str:
    """Render a complete Markdown report."""
    sections = [
        _header(data),
        _structure_map(data),
        _dependency_graph(data),
        _complexity_score(data),
        _fragility_score(data),
        _documentation_coverage(data),
        _improvement_list(data),
        _modernization_roadmap(data),
        _evidence_index(data),
    ]
    return "\n\n---\n\n".join(sections) + "\n"


def _header(data: ReportData) -> str:
    return (
        f"# PipelineAtlas Analysis Report\n\n"
        f"**Pipeline:** {data.graph.name}\n"
        f"**Generated:** {data.generated_at}\n"
        f"**Nodes:** {len(data.graph.nodes)} | "
        f"**Edges:** {len(data.graph.edges)} | "
        f"**Findings:** {len(data.findings)}"
    )


def _structure_map(data: ReportData) -> str:
    lines = ["## 1. Structure Map\n"]
    type_groups: dict[str, list[str]] = {}
    for node in data.graph.nodes:
        t = str(node.node_type)
        type_groups.setdefault(t, []).append(node.name)

    for node_type, names in sorted(type_groups.items()):
        lines.append(f"### {node_type.title()} ({len(names)})")
        for name in sorted(names):
            lines.append(f"- {name}")
        lines.append("")
    return "\n".join(lines)


def _dependency_graph(data: ReportData) -> str:
    lines = ["## 2. Dependency Graph\n"]
    if not data.graph.edges:
        lines.append("No dependencies detected.")
        return "\n".join(lines)

    lines.append("| Source | Edge Type | Target |")
    lines.append("|--------|-----------|--------|")
    node_map = {n.id: n.name for n in data.graph.nodes}
    for edge in data.graph.edges:
        src = node_map.get(edge.source_node_id, edge.source_node_id[:8])
        tgt = node_map.get(edge.target_node_id, edge.target_node_id[:8])
        lines.append(f"| {src} | {edge.edge_type} | {tgt} |")
    return "\n".join(lines)


def _complexity_score(data: ReportData) -> str:
    s = data.scores
    return (
        f"## 3. Complexity Score: **{s.complexity_score}**\n\n"
        f"| Metric | Value |\n"
        f"|--------|-------|\n"
        f"| Nodes | {s.node_count} |\n"
        f"| Edges | {s.edge_count} |\n"
        f"| Max Depth | {s.max_depth} |\n"
        f"| Max Fan-out | {s.max_fan_out} |"
    )


def _fragility_score(data: ReportData) -> str:
    s = data.scores
    return (
        f"## 4. Fragility Score: **{s.fragility_score}**\n\n"
        f"| Risk Factor | Count |\n"
        f"|------------|-------|\n"
        f"| Secrets | {s.secret_count} |\n"
        f"| Cross-triggers | {s.cross_trigger_count} |\n"
        f"| Unpinned images | {s.unpinned_image_count} |\n"
        f"| Missing doc types | {s.missing_doc_types} |"
    )


def _documentation_coverage(data: ReportData) -> str:
    doc_nodes = [n for n in data.graph.nodes if n.node_type == NodeType.DOC_FILE]
    total_expected = 5  # readme, architecture, runbook, security, codeowners
    found = len(doc_nodes)
    pct = round(found / total_expected * 100, 1) if total_expected > 0 else 0

    lines = [f"## 5. Documentation Coverage: **{pct}%**\n"]
    if doc_nodes:
        lines.append("| Document | Type |")
        lines.append("|----------|------|")
        for n in doc_nodes:
            doc_type = getattr(n, "doc_type", "unknown")
            lines.append(f"| {n.name} | {doc_type} |")
    else:
        lines.append("No documentation files detected.")
    return "\n".join(lines)


def _improvement_list(data: ReportData) -> str:
    lines = [f"## 6. Improvement List ({len(data.findings)} findings)\n"]
    if not data.findings:
        lines.append("No findings.")
        return "\n".join(lines)

    for i, f in enumerate(data.findings, 1):
        conf = getattr(f.confidence, "level", "unknown") if f.confidence else "unknown"
        lines.append(f"### {i}. [{f.severity.upper()}] {f.title}")
        lines.append(f"")
        lines.append(f"{f.description}")
        lines.append(f"")
        lines.append(f"**Confidence:** {conf} | **Rule:** `{f.rule_id}`")
        if f.recommendation:
            lines.append(f"")
            lines.append(f"> **Recommendation:** {f.recommendation}")
        lines.append("")
    return "\n".join(lines)


def _modernization_roadmap(data: ReportData) -> str:
    lines = ["## 7. Modernization Roadmap\n"]
    if data.modernization_notes:
        lines.append(data.modernization_notes)
    else:
        lines.append("*Modernization roadmap will be generated by `atlas-ai` in Phase 2.*")
    return "\n".join(lines)


def _evidence_index(data: ReportData) -> str:
    lines = ["## 8. Evidence Index\n"]
    evidence_items = []
    for f in data.findings:
        for ev in f.evidence:
            evidence_items.append((f.rule_id, f.title, ev.description))

    if not evidence_items:
        lines.append("No evidence collected.")
        return "\n".join(lines)

    lines.append("| # | Rule | Finding | Evidence |")
    lines.append("|---|------|---------|----------|")
    for i, (rule, title, desc) in enumerate(evidence_items, 1):
        lines.append(f"| {i} | `{rule}` | {title} | {desc} |")
    return "\n".join(lines)
