"""PDF report renderer — generates styled PDF from ReportData.

Uses pure-Python HTML-to-text generation to create a PDF-ready
document. In production, pair with weasyprint or reportlab.
"""

from __future__ import annotations

import logging
from typing import Any

from atlas_report.report_data import ReportData

logger = logging.getLogger(__name__)


def _html_header(title: str) -> str:
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{
    font-family: 'Segoe UI', system-ui, sans-serif;
    color: #1a1a2e;
    max-width: 800px;
    margin: 40px auto;
    padding: 0 20px;
    line-height: 1.6;
  }}
  h1 {{
    color: #16213e;
    border-bottom: 3px solid #0f3460;
    padding-bottom: 10px;
  }}
  h2 {{
    color: #0f3460;
    margin-top: 30px;
  }}
  .score-card {{
    display: inline-block;
    background: #f0f4ff;
    border-radius: 8px;
    padding: 12px 24px;
    margin: 8px;
    text-align: center;
    min-width: 140px;
  }}
  .score-label {{ font-size: 0.85em; color: #666; }}
  .score-value {{ font-size: 1.8em; font-weight: 700; }}
  .score-good {{ color: #10b981; }}
  .score-warn {{ color: #f59e0b; }}
  .score-bad {{ color: #ef4444; }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin: 16px 0;
  }}
  th, td {{
    border: 1px solid #ddd;
    padding: 8px 12px;
    text-align: left;
  }}
  th {{ background: #0f3460; color: white; }}
  tr:nth-child(even) {{ background: #f8f9fa; }}
  .footer {{
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #ddd;
    font-size: 0.85em;
    color: #999;
  }}
</style>
</head>
<body>
"""


def render_pdf_html(data: ReportData) -> str:
    """Render ReportData as styled HTML suitable for PDF conversion.

    This produces complete HTML that can be converted to PDF with
    weasyprint, wkhtmltopdf, or any HTML-to-PDF tool.
    """
    scores = data.scores
    graph = data.graph
    findings = data.findings

    html = _html_header(f"PipelineAtlas Report — {graph.name}")

    # Header
    html += f"<h1>🔍 PipelineAtlas Report</h1>\n"
    html += f"<p><strong>Pipeline:</strong> {graph.name}</p>\n"
    html += f"<p><strong>Scanned:</strong> {graph.scanned_at.isoformat()[:19]}</p>\n"

    # Score cards
    html += "<h2>Health Scores</h2>\n"
    html += "<div>\n"

    c_class = "score-good" if scores.complexity_score < 30 else ("score-warn" if scores.complexity_score < 60 else "score-bad")
    html += f'<div class="score-card"><div class="score-label">Complexity</div>'
    html += f'<div class="score-value {c_class}">{scores.complexity_score:.0f}</div></div>\n'

    f_class = "score-good" if scores.fragility_score < 30 else ("score-warn" if scores.fragility_score < 60 else "score-bad")
    html += f'<div class="score-card"><div class="score-label">Fragility</div>'
    html += f'<div class="score-value {f_class}">{scores.fragility_score:.0f}</div></div>\n'

    m_class = "score-good" if scores.maturity_score >= 60 else ("score-warn" if scores.maturity_score >= 30 else "score-bad")
    html += f'<div class="score-card"><div class="score-label">Maturity</div>'
    html += f'<div class="score-value {m_class}">{scores.maturity_score:.0f}</div></div>\n'
    html += "</div>\n"

    # Graph summary
    html += "<h2>Graph Summary</h2>\n"
    html += "<table>\n"
    html += "<tr><th>Metric</th><th>Value</th></tr>\n"
    html += f"<tr><td>Nodes</td><td>{len(graph.nodes)}</td></tr>\n"
    html += f"<tr><td>Edges</td><td>{len(graph.edges)}</td></tr>\n"
    html += f"<tr><td>Max Depth</td><td>{scores.max_depth}</td></tr>\n"
    html += f"<tr><td>Max Fan-out</td><td>{scores.max_fan_out}</td></tr>\n"
    html += "</table>\n"

    # Findings table
    if findings:
        html += f"<h2>Findings ({len(findings)})</h2>\n"
        html += "<table>\n"
        html += "<tr><th>Rule</th><th>Severity</th><th>Description</th></tr>\n"
        for f in findings:
            html += f"<tr><td>{f.rule_id}</td><td>{f.severity}</td><td>{f.title}</td></tr>\n"
        html += "</table>\n"

    # Footer
    html += '<div class="footer">\n'
    html += "<p>Generated by PipelineAtlas — CI/CD Architecture Intelligence Platform</p>\n"
    html += "</div>\n"
    html += "</body></html>"

    logger.info("PDF HTML rendered: %d characters", len(html))
    return html
